[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "14365 Programmer Documentation"
authors = [{name = "Logan Miller", email = "loganmiller5505@gmail.com"}]
dynamic = ["version", "description"]
